### ISSUE TITLE
unsupported operand type(s) for /: 'str' and 'int', write_SN_Latency/osd_node_count

### ISSUE THREAD

**Issue by hnuzhoulin** [01org/CeTune#53]
```python
Traceback (most recent call last):
  File "analyzer.py", line 591, in <module>
    main(sys.argv[1:])
  File "analyzer.py", line 587, in main
    func()
  File "analyzer.py", line 109, in process_data
    result = self.summary_result( result )
  File "analyzer.py", line 265, in summary_result
    tmp_data["SN_Latency(ms)"] = "%.3f" % write_SN_Latency/osd_node_count
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by xuechendi** [comment]
@hnuzhoulin , Hum, I ran into this problem days ago, it turns out python see the line
"%.3f" % write_SN_Latency/osd_node_count as do ("%.3f" % write_SN_Latency) first , then it will be divided by osd_node_count, I forgot to commit this fix, please modify this line to "%.3f" % (write_SN_Latency/osd_node_count), I will submit a fix later

And if you wanna rerun the analyzer, just do
cd analyzer; python analyzer.py --path ${the result dir} process_data

**Comment by hnuzhoulin** [comment]
Thanks
