### ISSUE TITLE
Virtual Image example

### ISSUE THREAD

**Issue by marcosmamorim** [01org/CeTune#59]
HI, 

First, congratulation this tool is perfect to test, I would like to know if you have example of vclient.tmp.img, and you have a fixed path into file prepare-vm.sh it's hard coded to your path address (/home/xuechendi/remote_access/vclient.tmp.img) Line: 63.

**Comment by xuechendi** [comment]
Hi, @marcosmamorim 

Sorry for my slow reply, I was on day off yesterday and totally forgot about this issue

About the vclient.tmp.img, you can create a basic ubuntu vm img, and put under CeTune/vm-scripts/ dir, then the prepare-vm.sh should work. 

Or, I uploaded a vclient.tmp.img to cloud, because of the size limitation of dropbox, I uploaded to a Chinese cloud storage web site, hope you can find where the download button is(tips: the white button right after the blue one, writes 下载(2.5G))

url :  http://pan.baidu.com/s/1dFflyDj

passwd:  q2d6

**Comment by Yanfeng-Wang** [comment]
But Baidu says， "你下载的文件过大，需要使用百度云管家"

**Comment by marcosmamorim** [comment]
Hi @xuechendi 

Thanks for reply, I created my own image and run the tests.
